name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests/

    - name: Build APK
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y git
        sudo apt-get install -y python3
        sudo apt-get install -y python3-pip
        sudo apt-get install -y libssl-dev libffi-dev libxml2 libxml2-dev libxslt1-dev zlib1g-dev liblzma-dev
        sudo apt-get install -y libjpeg8-dev libopenjp2-7-dev

        python -m pip install --upgrade buildozer
        buildozer -v android debug
